backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: "false" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Page d'accueil"
        name: "index"
        fields:
          - { label: "Template", name: "template", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/apropos.md"
        label: "À propos"
        name: "apropos"
        fields:
          - { label: "Template", name: "template", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/ressources.md"
        label: "Ressources"
        name: "ressources"
        fields:
          - { label: "Template", name: "template", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Files"
            name: "files"
            widget: "list"
            fields:
              - { label: "File name", name: "name", widget: "string" }
              - { label: "File path", name: "path", widget: "file" }

      - file: "src/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Template", name: "template", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
